
entities:

  # 1. The Target: Nipah G Protein (Frame 7)
  - file:
      id: nipah_g
      path: '../targets/frame_7.pdb'

      include:
        - chain:
            id: A

      binding_types:
        - chain:
            id: A
            binding: 52, 53, 54, 55, 201, 202, 215, 303, 304, 305, 314, 319, 343, 345, 346, 368, 370, 372, 394

  # 2. The Binder: To be designed
  - protein:
      id: binder
      sequence: 40..70
